# Generated by Django 5.2.14 on 2026-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author_book_app', '0002_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book_author',
            field=models.ManyToManyField(related_name='authors', to='Author_book_app.book'),
        ),
    ]
