# Generated by Django 5.2.14 on 2026-06-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsiterLogin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
