# Generated by Django 5.2.14 on 2026-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.TextField(),
        ),
    ]
