# Generated by Django 5.2.14 on 2026-06-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_game_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Arcade', 'Arcade'), ('Strategy', 'Strategy'), ('Adventure', 'Adventure')], max_length=255, null=True),
        ),
    ]
